spring:
  application:
    name: dart-scorer
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=dart-scorer
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: true
    default-schema: dart-scorer
server:
  port: 9091