spring:
  application:
    name: dart-scorer
  datasource:
    driver-class-name: org.h2.Driver
    username: admin
    password: password
    url: jdbc:h2:mem:dart-scorer
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    enabled: true
    default-schema: dart-scorer
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    default-property-inclusion: non_null
#  security:
#    user:
#      name: harsh
#      password: harsh
server:
  port: 9091
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql : trace